### ISSUE TITLE
TypeError: strptime() argument 1 must be str, not datetime.datetime after upgrading to 1.8.2

### ISSUE THREAD

**Issue by duduche59** [achillesrasquinha/pipupgrade#85] opened 2021-01-12 07:20 UTC
After upgrade to 1.8.2 on raspbian buster i have this issue
sudo pipupgrade 
Checking...

multiprocessing.pool.RemoteTraceback: 
"""
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.7/dist-packages/pipupgrade/model/package.py", line 116, in __init__
    time_difference	= to_datetime(res["_updated_at"]) + timedelta(seconds = cache_timeout)
  File "/usr/local/lib/python3.7/dist-packages/pipupgrade/model/package.py", line 69, in to_datetime
    return datetime.strptime(string, "%Y-%m-%d %H:%M:%S.%f")
TypeError: strptime() argument 1 must be str, not datetime.datetime
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.7/dist-packages/pipupgrade/commands/helper.py", line 333, in get_registry_from_pip
    build_dependency_tree = build_dependency_tree, jobs = jobs)
  File "/usr/local/lib/python3.7/dist-packages/pipupgrade/model/registry.py", line 111, in __init__
    for package in pool.imap_unordered(partial(Package, **args), packages):
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
TypeError: strptime() argument 1 must be str, not datetime.datetime
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pipupgrade/commands/__init__.py", line 75, in command
    return _command(**ARGUMENTS)
  File "/usr/local/lib/python3.7/dist-packages/pipupgrade/commands/__init__.py", line 207, in _command
    pip_path
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
TypeError: strptime() argument 1 must be str, not datetime.datetime

An error occured while performing the above command. This could be an issue with
"pipupgrade". Kindly post an issue at https://github.com/achillesrasquinha/pipupgrade/issues

Same issue on Linuxmint 20

**Comment by CDAGaming** [comment] 2021-01-14 14:01
Can confirm same issue on PopOs 20.04.1

**Comment by rakaw** [comment] 2021-01-26 18:31
I can confirm as well. Same issue on Manjaro 20.2.1
- Kernel: 5.10.10
- Python: 3.9.1

Using zombiepigdragon's temporariy fix to downgrade to pipupgrade ver. 1.7.4 works fine for now.

**Comment by CDAGaming** [comment] 2021-01-26 19:16
Bump. Effects 1.8.3 as well

CC: @achillesrasquinha since this is stopping usability of this, just like the last TypeError.

**Comment by achillesrasquinha** [comment] 2021-01-28 15:16
Hi guys! Could you please post a very fresh log of your latest command.

**Comment by rakaw** [comment] 2021-01-28 18:58
@achillesrasquinha here is the output for running pipupgrade ver. 1.8.4:



Checking...

multiprocessing.pool.RemoteTraceback: 
"""
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/rk/.local/lib/python3.9/site-packages/pipupgrade/model/package.py", line 116, in __init__
    time_difference	= to_datetime(res["_updated_at"]) + timedelta(seconds = cache_timeout)
  File "/home/rk/.local/lib/python3.9/site-packages/pipupgrade/model/package.py", line 69, in to_datetime
    return datetime.strptime(string, "%Y-%m-%d %H:%M:%S.%f")
TypeError: strptime() argument 1 must be str, not datetime.datetime
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/rk/.local/lib/python3.9/site-packages/pipupgrade/commands/helper.py", line 331, in get_registry_from_pip
    registry     = Registry(source = pip_path, packages = packages,
  File "/home/rk/.local/lib/python3.9/site-packages/pipupgrade/model/registry.py", line 111, in __init__
    for package in pool.imap_unordered(partial(Package, **args), packages):
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
TypeError: strptime() argument 1 must be str, not datetime.datetime
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rk/.local/lib/python3.9/site-packages/pipupgrade/commands/__init__.py", line 75, in command
    return _command(**ARGUMENTS)
  File "/home/rk/.local/lib/python3.9/site-packages/pipupgrade/commands/__init__.py", line 199, in _command
    for registry in pool.imap_unordered(
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
TypeError: strptime() argument 1 must be str, not datetime.datetime

An error occured while performing the above command. This could be an issue with
"pipupgrade". Kindly post an issue at https://github.com/achillesrasquinha/pipupgrade/issues

**Comment by duduche59** [comment] 2021-01-29 06:46
@achillesrasquinha Issue set to raspbian buster with version 1.8.4
On Linuxmint 20 : 
Checking...

multiprocessing.pool.RemoteTraceback: 
"""
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.8/dist-packages/pipupgrade/model/package.py", line 116, in __init__
    time_difference	= to_datetime(res["_updated_at"]) + timedelta(seconds = cache_timeout)
  File "/usr/local/lib/python3.8/dist-packages/pipupgrade/model/package.py", line 69, in to_datetime
    return datetime.strptime(string, "%Y-%m-%d %H:%M:%S.%f")
TypeError: strptime() argument 1 must be str, not datetime.datetime
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.8/dist-packages/pipupgrade/commands/helper.py", line 331, in get_registry_from_pip
    registry     = Registry(source = pip_path, packages = packages,
  File "/usr/local/lib/python3.8/dist-packages/pipupgrade/model/registry.py", line 111, in __init__
    for package in pool.imap_unordered(partial(Package, **args), packages):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
TypeError: strptime() argument 1 must be str, not datetime.datetime
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pipupgrade/commands/__init__.py", line 75, in command
    return _command(**ARGUMENTS)
  File "/usr/local/lib/python3.8/dist-packages/pipupgrade/commands/__init__.py", line 199, in _command
    for registry in pool.imap_unordered(
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
TypeError: strptime() argument 1 must be str, not datetime.datetime

An error occured while performing the above command. This could be an issue with
"pipupgrade". Kindly post an issue at https://github.com/achillesrasquinha/pipupgrade/issues

**Comment by shadowlmd** [comment] 2021-02-16 22:37
Wow, this is still not fixed..

**Comment by CDAGaming** [comment] 2021-02-18 19:21
> Wow, this is still not fixed..

It indeed is incredible, since this issue as well as the last one meant I haven't been able to use this product for the last month or so. Very likely I'll be discouraging further use of this package, or just fork it privately to fix it myself at this point, if even with multiple logs and multiple versions effected, that the owner is unable to fix this.

**Comment by CDAGaming** [comment] 2021-02-27 04:36
Issue confirmed fixed as of new testing on 1.9.0

Reproduction is recommended if anyone still faces this.

**Comment by achillesrasquinha** [comment] 2021-03-03 00:58
Closing since fixed. Please reopen if issues.

**Closed by achillesrasquinha** 2021-03-03 00:58 UTC
